catalog/urls.py
from django.urls import path
from catalog.views import HomeView, ContactsView, ProductsView, CategoryProductsView, ProductDetailsView, \
    CreateProductView, BlogPostListView, BlogPostCreateView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView, \
    MailingSettingsCreateView, MailingSettingsListView, VersionCreateView, MailingSettingsUpdateView, \
    MailingSettingsDeleteView, MailingSettingsDetailView, UpdateProductView

app_name = 'catalog'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('products/', ProductsView.as_view(), name='products'),
    path('category/<int:category_id>/', CategoryProductsView.as_view(), name='category_products'),
    path('product/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/create/', CreateProductView.as_view(), name='product_create'),
    path('products/edit/<int:pk>/', UpdateProductView.as_view(), name='product_edit'),

    path('blog/', BlogPostListView.as_view(), name='blogpost_list'),
    path('blog/create/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('blog/view/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_view'),
    path('blog/edit/<int:pk>/', BlogPostUpdateView.as_view(), name='blogpost_edit'),
    path('blog/delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),
    path('mailing/settings/view/', MailingSettingsListView.as_view(), name='mailing_list'),
    path('mailing/settings/<int:pk>/edit/', MailingSettingsUpdateView.as_view(), name='mailing_settings_update'),
    path('mailing/settings/<int:pk>/delete/', MailingSettingsDeleteView.as_view(), name='mailing_settings_delete'),
    path('mailing/settings/create/', MailingSettingsCreateView.as_view(), name='mailing_settings_create'),
    path('mailing/settings/<int:pk>/', MailingSettingsDetailView.as_view(), name='mailing_details'),
    path('version/create/<int:product_id>/', VersionCreateView.as_view(), name='create_version'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('users/', include('users.urls', namespace='users')),
                  path('users/', include('users.urls', namespace='users')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, VerifyEmailView, ConfirmEmailView, ConfirmationSuccessView, \
    ConfirmationErrorView, CreationErrorView, ChangePasswordView, GenerateAndSendPasswordView

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('users/verify_email/', VerifyEmailView.as_view(), name='verification_email'),
    path('confirm_email/<str:token>/', ConfirmEmailView.as_view(), name='confirm_email'),
    path('error_create/', CreationErrorView.as_view(), name='error_create'),
    path('confirmation_success/', ConfirmationSuccessView.as_view(), name='confirmation_success'),
    path('confirmation_error/', ConfirmationErrorView.as_view(), name='confirmation_error'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('generate_send_password/', GenerateAndSendPasswordView.as_view(), name='generate_send_password'),

]

catalog/models.py
from django.db import models
from django.utils import timezone

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    objects = models.Manager()

    def __str__(self):
        return f'{self.name}: {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    preview = models.ImageField(upload_to='previews/', verbose_name='Превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    creation_date = models.DateField(verbose_name='Дата создания')
    last_change_date = models.DateField(verbose_name='Дата последнего изменения')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Создатель')
    active_version = models.OneToOneField('Version', related_name='+', **NULLABLE, on_delete=models.SET_NULL)
    is_published = models.BooleanField(default=False)
    objects = models.Manager()

    def save(self, *args, **kwargs):
        if not self.creation_date:
            self.creation_date = timezone.now().date()
        self.last_change_date = timezone.now().date()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}: {self.price} {self.description}'

    class Meta:
        permissions = [
            ("can_set_product_publication", "Can set product publication"),
            ("can_change_product_description", "Can change product description"),
            ("can_change_product_category", "Can change product category"),
        ]

        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    email = models.CharField(max_length=100, verbose_name='Почта')
    message = models.TextField(verbose_name='Текст', **NULLABLE)
    objects = models.Manager()

    def __str__(self):
        return f'{self.name}: {self.email}'

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class BlogPost(models.Model):
    title = models.CharField(max_length=300, verbose_name='Заголовок')
    slug = models.CharField(max_length=300, verbose_name='Slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog_previews/', verbose_name='Превью', **NULLABLE)
    created_date = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True)
    views_count = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.title}: {self.content}'

    class Meta:
        verbose_name = 'Запись блога'
        verbose_name_plural = 'Записи блога'
        ordering = ['-created_date']


class MailingMessage(models.Model):
    subject = models.CharField(max_length=100, verbose_name='Тема')
    message_content = models.TextField(verbose_name='Содержание')
    objects = models.Manager()

    def __str__(self):
        return f'{self.subject}:\n {self.message_content}'

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class Client(models.Model):
    full_name = models.CharField(max_length=100, verbose_name='ФИО')
    email = models.EmailField(max_length=100, verbose_name='Почта')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    objects = models.Manager()

    def __str__(self):
        return f'{self.full_name}: {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class MailingSettings(models.Model):
    objects = models.Manager()
    DELIVERY_FREQUENCY_CHOICES = (
        ('daily', 'Ежедневная'),
        ('weekly', 'Еженедельная'),
        ('monthly', 'Ежемесячная'),
    )
    DELIVERY_STATUS_CHOICES = (
        ('completed', 'Завершена'),
        ('created', 'Создана'),
        ('running', 'Запущена'),
    )
    start_time = models.DateTimeField(blank=True)
    end_time = models.DateTimeField(default=None)
    frequency = models.CharField(max_length=20, choices=DELIVERY_FREQUENCY_CHOICES, default='weekly')
    status = models.CharField(max_length=20, choices=DELIVERY_STATUS_CHOICES, default='created')
    message = models.ForeignKey(MailingMessage, on_delete=models.CASCADE,
                                verbose_name='Сообщение для рассылки', **NULLABLE)
    client = models.ManyToManyField(Client,
                                    verbose_name='Клиент рассылки')

    def __str__(self):
        return f"{self.frequency} рассылка в {self.start_time} {self.client}"

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class EmailLog(models.Model):
    STATUSES = (
        ('STATUS_OK', 'Успешно'),
        ('STATUS_FAILED', 'Ошибка'),
    )
    datetime_attempt = models.DateTimeField(auto_now_add=True, verbose_name='Последняя попытка')
    status = models.CharField(choices=STATUSES, default='STATUS_OK', verbose_name='Статус')
    client = models.ManyToManyField(Client, verbose_name='Клиент')
    settings = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='Настройки', **NULLABLE)
    objects = models.Manager()

    def __str__(self):
        return f'Логи рассылки - {self.status}'

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылки'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    version_number = models.CharField(max_length=50, verbose_name='Номер версии')
    version_name = models.CharField(max_length=100, verbose_name='Название версии')
    is_current = models.BooleanField(default=False, verbose_name='Текущая версия')

    objects = models.Manager()

    def __str__(self):
        return f"{self.product} - {self.version_number}"

catalog/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from catalog.models import Product, BlogPost, Version, Client, MailingMessage, MailingSettings
from django import forms


class CreateProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('создать', 'Создать'))

    def form_invalid(self):
        self.error = 'Неверная форма'

    def clean_name(self):
        name = self.cleaned_data['name']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for word in forbidden_words:
            if word in name.lower():
                raise forms.ValidationError("Название содержит запрещенное слово.")
        return name

    def clean_description(self):
        description = self.cleaned_data['description']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for word in forbidden_words:
            if word in description.lower():
                raise forms.ValidationError("Описание содержит запрещенное слово.")
        return description

    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('user',)


class CreateTestProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('обновить', 'Обновить'))

    class Meta:
        model = Product
        fields = ['description', 'name', 'is_published']


class BlogPostForm(forms.ModelForm):
    preview = forms.ImageField(label='Загрузить изображение')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

    class Meta:
        model = BlogPost
        fields = ['title', 'content', 'preview']

    # start_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    # end_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))


class MailingSettingsCreateForm(forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = '__all__'
        widgets = {
            'start_time': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'end_time': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'frequency': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'message': forms.Select(attrs={'class': 'form-control'}),
        }


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ['product', 'version_number', 'version_name', 'is_current']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Сохранить'))

    def clean(self):
        cleaned_data = super().clean()
        is_current = cleaned_data.get('is_current')
        product = cleaned_data.get('product')

        if is_current and Version.objects.filter(product=product, is_current=True).count() > 1:
            raise forms.ValidationError('Может быть только одна текущая версия для данного продукта.')

        return cleaned_data

    def clean_is_current(self):
        is_current = self.cleaned_data.get('is_current')
        if is_current is None:
            is_current = False
        return is_current

catalog/templates/catalog/includes/inc_catalog_mailing.html
{% load my_tags %}
{% block content %}
<div class="col-md-6">
    <div class="card mb-4">
        <div class="card-body">
            <h3 class="card-title">{{ mailing_client.get_frequency_display }} рассылка </h3>
            <p>{{ mailing_client.start_time }} - {{ mailing_client.end_time }}</p>
            <h4>Клиенты рассылки</h4>
            {% for client in mailing_client.client.all %}
            <div>
                <h6>{{ client }}</h6>

            </div>
            {% empty %}
            <p>Нет связанных клиентов.</p>
            {% endfor %}


            <h4>Сообщение рассылки:</h4>
            <p>{{ mailing_client.message }}</p>
            <h5>{{ mailing_client.get_status_display }}</h5>
            <a href="{% url 'catalog:mailing_details' mailing_client.id %}"
               class="btn btn-primary">Подробнее</a>
            <a href="{% url 'catalog:mailing_settings_update' mailing_client.id %}"
               class="btn btn-info">Редактировать</a>
            <a href="{% url 'catalog:mailing_settings_delete' mailing_client.id %}" class="btn btn-dark">Удалить</a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/includes/inc_catalog_menu.html
<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">О нас</h4>
                    <p class="text-muted">Мы классный интернет магазин, где вы можете купить все, что угодно.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'catalog:home' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'catalog:contacts' %}" class="text-white">Напишите нам</a></li>
                        <li><a href="{% url 'catalog:products' %}" class="text-white">Товары</a></li>
                        <li><a href="{% url 'catalog:blogpost_list' %}" class="text-white">Отзывы</a></li>

                        {% if user.is_authenticated %}
                        <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
                        <li><a href="{% url 'catalog:mailing_settings_create' %}" class="text-white">Создать
                            рассылку</a></li>
                        <li><a href="{% url 'catalog:mailing_list' %}" class="text-white">Список рассылок</a></li>
                        <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                        {% else %}
                        <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                        <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Интернет-магазин для души</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

catalog/templates/catalog/includes/inc_catalog_product.html
{% load my_tags %}
<html lang="ru">
<body>
{% block content %}
<div class="col-md-6">
        <div class="card mb-4">
            <div class="card-body">
                <h3 class="card-title">{{ product.name }}</h3>
                <p class="card-text">Цена: {{ product.price }}</p>
                <p class="card-text">Описание: {{ product.description|slice:":100" }}</p>
                <p class="card-text">Категория: <a href="{% url 'catalog:category_products' category_id=product.category.id %}">{{ product.category.name }}</a></p>
                 {% if product.active_version %}
        <p>Активная версия: {{ product.active_version.version_number }}</p>
    {% else %}
        <p>Нет активной версии</p>
    {% endif %}
                <a href="{% url 'catalog:product_details' product.id %}" class="btn btn-primary">Подробнее</a>
            </div>
            <img src="{{ product.preview|mymedia }}" alt="Изображение" class="card-img-right img-fluid" style="max-width: 200px;">
        </div>
    </div>
{% endblock %}
</body>
</html>