catalog/urls.py
from django.urls import path
from catalog.views import HomeView, ContactsView, ProductsView, CategoryProductsView, ProductDetailsView, \
    CreateProductView, BlogPostListView, BlogPostCreateView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView, \
    MailingSettingsCreateView, MailingSettingsListView, VersionCreateView, MailingSettingsUpdateView, \
    MailingSettingsDeleteView, MailingSettingsDetailView, UpdateProductView

app_name = 'catalog'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('products/', ProductsView.as_view(), name='products'),
    path('category/<int:category_id>/', CategoryProductsView.as_view(), name='category_products'),
    path('product/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/create/', CreateProductView.as_view(), name='product_create'),
    path('products/edit/<int:pk>/', UpdateProductView.as_view(), name='product_edit'),

    path('blog/', BlogPostListView.as_view(), name='blogpost_list'),
    path('blog/create/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('blog/view/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_view'),
    path('blog/edit/<int:pk>/', BlogPostUpdateView.as_view(), name='blogpost_edit'),
    path('blog/delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),
    path('mailing/settings/view/', MailingSettingsListView.as_view(), name='mailing_list'),
    path('mailing/settings/<int:pk>/edit/', MailingSettingsUpdateView.as_view(), name='mailing_settings_update'),
    path('mailing/settings/<int:pk>/delete/', MailingSettingsDeleteView.as_view(), name='mailing_settings_delete'),
    path('mailing/settings/create/', MailingSettingsCreateView.as_view(), name='mailing_settings_create'),
    path('mailing/settings/<int:pk>/', MailingSettingsDetailView.as_view(), name='mailing_details'),
    path('version/create/<int:product_id>/', VersionCreateView.as_view(), name='create_version'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('users/', include('users.urls', namespace='users')),
                  path('users/', include('users.urls', namespace='users')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, VerifyEmailView, ConfirmEmailView, ConfirmationSuccessView, \
    ConfirmationErrorView, CreationErrorView, ChangePasswordView, GenerateAndSendPasswordView

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('users/verify_email/', VerifyEmailView.as_view(), name='verification_email'),
    path('confirm_email/<str:token>/', ConfirmEmailView.as_view(), name='confirm_email'),
    path('error_create/', CreationErrorView.as_view(), name='error_create'),
    path('confirmation_success/', ConfirmationSuccessView.as_view(), name='confirmation_success'),
    path('confirmation_error/', ConfirmationErrorView.as_view(), name='confirmation_error'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('generate_send_password/', GenerateAndSendPasswordView.as_view(), name='generate_send_password'),

]

catalog/models.py
from django.db import models
from django.utils import timezone

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    objects = models.Manager()

    def __str__(self):
        return f'{self.name}: {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    preview = models.ImageField(upload_to='previews/', verbose_name='Превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    creation_date = models.DateField(verbose_name='Дата создания')
    last_change_date = models.DateField(verbose_name='Дата последнего изменения')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Создатель')
    active_version = models.OneToOneField('Version', related_name='+', **NULLABLE, on_delete=models.SET_NULL)
    is_published = models.BooleanField(default=False)
    objects = models.Manager()

    def save(self, *args, **kwargs):
        if not self.creation_date:
            self.creation_date = timezone.now().date()
        self.last_change_date = timezone.now().date()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}: {self.price} {self.description}'

    class Meta:
        permissions = [
            ("can_set_product_publication", "Can set product publication"),
            ("can_change_product_description", "Can change product description"),
            ("can_change_product_category", "Can change product category"),
        ]

        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    email = models.CharField(max_length=100, verbose_name='Почта')
    message = models.TextField(verbose_name='Текст', **NULLABLE)
    objects = models.Manager()

    def __str__(self):
        return f'{self.name}: {self.email}'

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class BlogPost(models.Model):
    title = models.CharField(max_length=300, verbose_name='Заголовок')
    slug = models.CharField(max_length=300, verbose_name='Slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog_previews/', verbose_name='Превью', **NULLABLE)
    created_date = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True)
    views_count = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.title}: {self.content}'

    class Meta:
        verbose_name = 'Запись блога'
        verbose_name_plural = 'Записи блога'
        ordering = ['-created_date']


class MailingMessage(models.Model):
    subject = models.CharField(max_length=100, verbose_name='Тема')
    message_content = models.TextField(verbose_name='Содержание')
    objects = models.Manager()

    def __str__(self):
        return f'{self.subject}:\n {self.message_content}'

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class Client(models.Model):
    full_name = models.CharField(max_length=100, verbose_name='ФИО')
    email = models.EmailField(max_length=100, verbose_name='Почта')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    objects = models.Manager()

    def __str__(self):
        return f'{self.full_name}: {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class MailingSettings(models.Model):
    objects = models.Manager()
    DELIVERY_FREQUENCY_CHOICES = (
        ('daily', 'Ежедневная'),
        ('weekly', 'Еженедельная'),
        ('monthly', 'Ежемесячная'),
    )
    DELIVERY_STATUS_CHOICES = (
        ('completed', 'Завершена'),
        ('created', 'Создана'),
        ('running', 'Запущена'),
    )
    start_time = models.DateTimeField(blank=True)
    end_time = models.DateTimeField(default=None)
    frequency = models.CharField(max_length=20, choices=DELIVERY_FREQUENCY_CHOICES, default='weekly')
    status = models.CharField(max_length=20, choices=DELIVERY_STATUS_CHOICES, default='created')
    message = models.ForeignKey(MailingMessage, on_delete=models.CASCADE,
                                verbose_name='Сообщение для рассылки', **NULLABLE)
    client = models.ManyToManyField(Client,
                                    verbose_name='Клиент рассылки')

    def __str__(self):
        return f"{self.frequency} рассылка в {self.start_time} {self.client}"

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class EmailLog(models.Model):
    STATUSES = (
        ('STATUS_OK', 'Успешно'),
        ('STATUS_FAILED', 'Ошибка'),
    )
    datetime_attempt = models.DateTimeField(auto_now_add=True, verbose_name='Последняя попытка')
    status = models.CharField(choices=STATUSES, default='STATUS_OK', verbose_name='Статус')
    client = models.ManyToManyField(Client, verbose_name='Клиент')
    settings = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='Настройки', **NULLABLE)
    objects = models.Manager()

    def __str__(self):
        return f'Логи рассылки - {self.status}'

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылки'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    version_number = models.CharField(max_length=50, verbose_name='Номер версии')
    version_name = models.CharField(max_length=100, verbose_name='Название версии')
    is_current = models.BooleanField(default=False, verbose_name='Текущая версия')

    objects = models.Manager()

    def __str__(self):
        return f"{self.product} - {self.version_number}"

catalog/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from catalog.models import Product, BlogPost, Version, Client, MailingMessage, MailingSettings
from django import forms


class CreateProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('создать', 'Создать'))

    def form_invalid(self):
        self.error = 'Неверная форма'

    def clean_name(self):
        name = self.cleaned_data['name']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for word in forbidden_words:
            if word in name.lower():
                raise forms.ValidationError("Название содержит запрещенное слово.")
        return name

    def clean_description(self):
        description = self.cleaned_data['description']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for word in forbidden_words:
            if word in description.lower():
                raise forms.ValidationError("Описание содержит запрещенное слово.")
        return description

    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('user',)


class CreateTestProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('обновить', 'Обновить'))

    class Meta:
        model = Product
        fields = ['description', 'name', 'is_published']


class BlogPostForm(forms.ModelForm):
    preview = forms.ImageField(label='Загрузить изображение')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

    class Meta:
        model = BlogPost
        fields = ['title', 'content', 'preview']

    # start_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    # end_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))


class MailingSettingsCreateForm(forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = '__all__'
        widgets = {
            'start_time': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'end_time': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'frequency': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'message': forms.Select(attrs={'class': 'form-control'}),
        }


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ['product', 'version_number', 'version_name', 'is_current']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Сохранить'))

    def clean(self):
        cleaned_data = super().clean()
        is_current = cleaned_data.get('is_current')
        product = cleaned_data.get('product')

        if is_current and Version.objects.filter(product=product, is_current=True).count() > 1:
            raise forms.ValidationError('Может быть только одна текущая версия для данного продукта.')

        return cleaned_data

    def clean_is_current(self):
        is_current = self.cleaned_data.get('is_current')
        if is_current is None:
            is_current = False
        return is_current

catalog/templates/catalog/base.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Версия v4.0.0">
    <meta name="author" content="Алисочка">

    <title></title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/album.css'%}" rel="stylesheet">
</head>
<body>

{% include 'catalog/includes/inc_catalog_menu.html' %}

{% block content %}
{% endblock %}

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>&copy; 2023 - {% now 'Y' %}</p>

    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blogpost_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Подтвердите удаление отзыва "{{ blogpost.title }}"</p>
                            <button type="submit" class="btn btn-dark">Подтвердить</button>
                            <a href="{% url 'catalog:blogpost_list' %}" class="btn btn-info">Отменить</a>

                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

catalog/templates/catalog/blogpost_details.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">{{ blogposts.title }}</h2>
            <p class="card-text"><strong>Контент:</strong><br>{{ blogposts.content }}</p>
            <img src="{{ blogposts.preview|mymedia_blog }}" alt="Изображение" class="card-img-right img-fluid"
                 style="max-width: 200px;"><br>
            <div class="card-footer">
                Просмотры: {{ object.views_count }}</div><br>
            <a href="{% url 'catalog:blogpost_edit' blogposts.id %}" class="btn btn-primary">Редактировать</a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/category_products.html
{% extends 'catalog/base.html' %}
{% block content %}
{% for product in category_products_list %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">{{ product.name }}</h2>
            <p class="card-text">Цена: {{ product.price }}</p>
            <p class="card-text">Описание: {{ product.description }}</p>
            <p class="card-text">Категория: <a href="{% url 'catalog:category_products' category_id=category.id %}">{{ category.name }}</a></p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
<html lang="ru">
<body>
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div>
                    <h3>{{ title }}</h3>
                    <ul>
                        {% for contact in all_contacts %}
                        <li>
                            <p>Имя: {{ contact.name }}</p>
                            <p>Почта: {{ contact.email }}</p>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md-8">
                <form method="post" action="{% url 'catalog:contacts' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputName1" class="form-label">Ваше имя</label>
                        <input type="text" class="form-control" name="name">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Ваша почта</label>
                        <input type="email" class="form-control" name="email">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputtext1" class="form-label">Обратная связь</label>
                        <textarea class="form-control" name="message"></textarea>
                    </div>
                    <input type="submit" class="btn btn-primary" value="Отправить">
                </form>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}
</html>

catalog/templates/catalog/create_blog_post.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            <style>
                                /* Стили для полей формы */
                                input[type="text"],
                                select,
                                textarea {
                                    width: 100%;
                                    padding: 10px;
                                    border: 1px solid #ccc;
                                    border-radius: 4px;
                                    box-sizing: border-box;
                                    margin-bottom: 10px;
                                }

                                /* Стили для кнопки отправки формы */
                                button[type="submit"] {
                                    background-color: #4CAF50;
                                    color: white;
                                    padding: 10px 20px;
                                    border: none;
                                    border-radius: 4px;
                                    cursor: pointer;
                                }

                                /* Стили для меток полей */
                                label {
                                    display: block;
                                    font-weight: bold;
                                    margin-bottom: 5px;
                                }
                            </style>
                            {{ form.as_p }}
                            <button type="submit">
                                {% if blogpost %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                            <span>{{ form.errors }}</span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/create_version.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% crispy form %}
</form>
{% endblock %}

catalog/templates/catalog/mailing_details.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">{{ mailing.get_frequency_display }} рассылка </h2>
            <h6 class="card-title">Статус: {{ mailing.get_status_display }}</h6>
            <h4>Клиенты рассылки:</h4>
                {% for client in mailing.client.all %}
            <div>
                <h6> Имя: {{ client.full_name }}</h6>
                <p>Почта: {{ client.email }}</p>
                <p>Комментарий: {{ client.comment }}</p>
            </div>
            {% empty %}
            <p>Нет связанных клиентов.</p>
            {% endfor %}
            <h4>Время рассылки:</h4>
            <p>{{ mailing.start_time }} - {{ mailing.end_time }}</p>
            <h4>Сообщение рассылки:</h4>
            <p>{{ mailing.message.subject }}: {{ mailing.message.message_content }}</p>


            <div class="dropdown">
                <button class="btn btn-block btn-primary dropdown-toggle" type="button" id="addDropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Редактирование
                </button>
                <div class="dropdown-menu" aria-labelledby="addDropdown">
                    <a href="{% url 'catalog:mailing_settings_delete' mailing.id %}"
                       class="btn btn-dark">Удалить</a>
                    <a href="{% url 'catalog:mailing_settings_update' mailing.id %}"
                       class="btn btn-info">Редактировать</a>
                </div>
            </div>

        </div>
    </div>
</div>


{% endblock %}

catalog/templates/catalog/mailing_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<h1>Список рассылок</h1>
{% for mailing_client in mailing_clients %}
{% include 'catalog/includes/inc_catalog_mailing.html' %}

{% endfor %}<br>
<a href="{% url 'catalog:mailing_settings_create' %}">Создать новую рассылку</a>

{% endblock %}

catalog/templates/catalog/mailing_settings_create.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h3>Настройки рассылки</h3>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit">
                            Сохранить
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/mailingclient_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Вы уверены, что хотите удалить данную рассылку?</p>
                            <button type="submit" class="btn btn-dark">Подтвердить</button>
                            <a href="{% url 'catalog:blogpost_list' %}" class="btn btn-info">Отменить</a>

                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

catalog/templates/catalog/product_create.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% crispy form %}
                            {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                                {% for error in form.non_field_errors %}
                                {{ error }}
                                {% endfor %}
                            </div>
                            {% endif %}
                            <span>{{ error }}</span>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_details.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">{{ product.name }}</h2>
            <p class="card-text">Цена: {{ product.price }}</p>
            <p class="card-text">Описание: {{ product.description }}</p>
            <p class="card-text">Категория: <a href="{% url 'catalog:category_products' category_id=product.category.id %}">{{ product.category.name }}</a></p>
            <img src="{{ product.preview|mymedia }}" alt="Изображение" class="card-img-right img-fluid" style="max-width: 200px;">

        </div>
    </div>
    <div class="add-product-button">
    <div class="dropdown">
        <button class="btn btn-block btn-primary dropdown-toggle" type="button" id="addDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Добавить
        </button>
        <div class="dropdown-menu" aria-labelledby="addDropdown">
            <a class="dropdown-item" href="{% url 'catalog:blogpost_create' %}">Отзыв</a>
            <a class="dropdown-item" href="{% url 'catalog:create_version' product_id=product.id %}">Версию</a>
            <a class="dropdown-item" href="{% url 'catalog:product_edit' product.id %}">Изменить</a>
        </div>
    </div>
</div>
</div>


{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/base.html' %}
<html lang="ru">
<body>
{% block content %}
<div class="add-product-button">
    <a href="{% url 'catalog:product_create' %}" class="btn btn-block btn-primary">Добавить товар</a>
</div>
{% for product in products %}
    {% include 'catalog/includes/inc_catalog_product.html' %}
{% endfor %}

<!-- Отображение пагинации -->
<div class="pagination">
    <span class="step-links">
        {% if products.has_previous %}
            <a href="?page=1">&laquo; Первая</a>
            <a href="?page={{ products.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current-page">{{ products.number }}</span>

        {% if products.has_next %}
            <a href="?page={{ products.next_page_number }}">Следующая</a>
            <a href="?page={{ products.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}
</body>
</html>